---
- name: Copy tar
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: Start server
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls
