Parameters:
  Project:
    Description: Project name
    Type: String
    Default: Acme

  PrometheusHostAMI:
    Description: The machine image to be used for Prometheus host.
    Type: String
    Default: ami-05e1e66d082e56118

  PrometheusHostInstanceType:
    Description: The Prometheus host EC2 instance type to be used.
    Type: String
    Default: t3.micro

  PrometheusHostKeyName:
    Description: Name of an existing KeyPair to enable SSH access to the web servers from Prometheus host.
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: udacity

Resources:
  PrometheusHostSecGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH access via port 22 to web servers"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0

  PrometheusHost:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref PrometheusHostAMI
      InstanceType: !Ref PrometheusHostInstanceType
      SecurityGroupIds:
        - !Ref PrometheusHostSecGroup
      KeyName: !Ref PrometheusHostKeyName
    DependsOn:
      - PrometheusHostSecGroup

Outputs:

  PrometheusHostIp:
    Description: PrometheusHost Public IP
    Value: !GetAtt PrometheusHost.PublicIp

